esphome:
  name: esp8266-dk-ingresso
  comment: Sensore movimento ingresso andrea danimarca


esp8266:
  board: d1_mini_lite

# Enable logging
logger:

mqtt:
  broker: !secret mqtt_broker
  
  
# Enable Home Assistant API
# api:
#   encryption:
#     key: "S/OGno2S6t7t7GGrajPE3yWhktoCW+U7LwFL95h/7GY="


ota:
  password: "5bda3bca66e736daa257da373f1f8d57"

wifi:
  ssid: !secret wifi_ssid_dk
  password: !secret wifi_password_dk

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp8266-dk-ingresso"
    password: "Pippero64"
    
captive_portal:


binary_sensor:
  - platform: gpio
    pin: D2
    name: "Sensore Movimento Ingresso Danimarca"
    device_class: motion



sensor:
  - platform: wifi_signal
    name: "WiFi Signal esp8266-dk-ingresso"
    update_interval: 60s
    filters:
    - quantile:
        window_size: 7
        send_every: 4
        send_first_at: 3
        quantile: .9
      