esphome:
  name: irrigazione-laboratorio
  comment: Controllore Irrigazione e misurazione pioggia
  on_boot:
    then:
      - switch.turn_on: switch_irrigazione

esp8266:
  board: d1_mini_lite

# Enable logging
logger:

mqtt:
  broker: !secret mqtt_broker

# Enable Home Assistant API
#api:
 # encryption:
  #  key: "+pjtvtH3iTBOZsV0egn7qrXNsXqikcFzVZx1Z9KRPQc="

ota:
  password: "79f5e312f4e6bf83a449a81002f80750"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Irrigazione-Laboratorio"
    password: "FgVMZEuHvq0s"

captive_portal:

time:
            
  - platform: sntp
    timezone: IT
    id: sntp_time_reset_switch_irrigazione
    on_time:
      # Alle 10 di mattina resetto lo switch
      - seconds: 0
        minutes: 0
        hours: 10
        then:
          switch.turn_on: switch_irrigazione
    
    
sensor:
  - platform: pulse_counter
    pin: D7
    name: "10 Minutes Rain"
    id: recorded_rain
    unit_of_measurement: 'mm (L/m2)'
    update_interval: 600s
    accuracy_decimals: 2
    icon: "mdi:weather-rainy"
    internal_filter: 2s
    count_mode: 
      falling_edge: DISABLE
      rising_edge: INCREMENT
    filters:
        - multiply: 0.436251  # min * (557.05/ (r2 in millimetri)) considerando 1.75 millimetri per tip del bucket
    # total:
    #   unit_of_measurement: 'mm (L/m2)'
    #   name: 'Daily Rain'
    #   id: recorded_rain_total
    #   accuracy_decimals: 2
    #   icon: "mdi:bucket-outline"
    #   filters:
    #     - multiply: 0.0436251 # (557.05/ (r2 in millimetri)) considerando 1.75 millimetri per tip del bucket (dividi rispetto ai minuti rispetto a quello sopra)
      
  # - platform: pulse_meter
  #   pin: D2
  #   unit_of_measurement: 'kW'
  #   name: 'Electricity Usage'
  #   id: recorded_rain_total
  #   internal_filter: 100ms
  #   accuracy_decimals: 1

    # total:
    #   name: "Electricity Total"
    #   unit_of_measurement: "kWh"
    #   accuracy_decimals: 1

      

      
  - platform: wifi_signal
    name: "WiFi Signal irrigazione-laboratorio"
    update_interval: 60s
    filters:
      - quantile:
          window_size: 7
          send_every: 4
          send_first_at: 3
          quantile: .9
    
switch:
  - platform: gpio
    name: "Irrigazione"
    pin: D6
    id: switch_irrigazione
    icon: "mdi:watering-can"
    inverted: true