esphome:
  name: qualita-aria-salotto
  comment: Sensore qualita aria IKEA salotto e temperatura 
  on_boot:
    then:
      - output.turn_off: gpio_D6_ground

esp8266:
  board: d1_mini_lite

# Enable logging
logger:

mqtt:
  broker: !secret mqtt_broker
  
  
# Enable Home Assistant API
# api:
#   encryption:
#     key: "S/OGno2S6t7t7GGrajPE3yWhktoCW+U7LwFL95h/7GY="


ota:
  password: "5bda3bca66e736daa257da373f1f8d57"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.8.173
    gateway: 192.168.8.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1
    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Qualita-Aria-Salotto"
    password: "DxY7zFij11u6"

captive_portal:


output:
  - platform: gpio
    pin: D6
    id: gpio_D6_ground

uart:
  rx_pin: D4
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Qualita Aria Salotto"
      
  - platform: dht
    pin: D7
    model: AM2302
    temperature:
      name: "Temperatura Salotto IKEA"
      filters:
        median:
          window_size: 5
          send_every: 3
          send_first_at: 1
    humidity:
      name: "Umidita Salotto IKEA"
      filters:
        median:
          window_size: 5
          send_every: 3
          send_first_at: 1
    update_interval: 30s
    
  - platform: wifi_signal
    name: "WiFi Signal qualita-aria-salotto"
    update_interval: 60s
    filters:
    - quantile:
        window_size: 7
        send_every: 4
        send_first_at: 3
        quantile: .9
    