esphome:
  name: termovalvole-taverna
  comment: Taverna ESP8266 Controllore termovalvole\
  on_boot:
    then:
      - output.turn_off: gpio_d0_ground

esp8266:
  board: d1_mini_lite

# Enable logging
logger:

# Enable Home Assistant API 
#api:
  #password: ""

mqtt:
  broker: myhomeipdk.hopto.org

ota:
  password: "b9fe3f457d5dbd19fc190097db7f38e5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Termovalvole-Taverna"
    password: "IZupMzz1qORR"

captive_portal:


switch:
  - platform: gpio
    name: "Termovalvola Taverna"
    id: termovalvola_taverna
    pin: D1
    icon: "mdi:radiator"
    
    
sensor:
  - platform: wifi_signal
    name: "WiFi Signal termovalvole-taverna"
    update_interval: 60s
    filters:
      - quantile:
          window_size: 7
          send_every: 4
          send_first_at: 3
          quantile: .9

output:
  - platform: gpio
    pin: D0
    id: gpio_d0_ground


binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode:
        input: true
        pullup: true
      inverted: false
    name: Termostato Muro Taverna
    on_press:
      - switch.turn_on: termovalvola_taverna
      
    on_release:
      - switch.turn_off: termovalvola_taverna