esphome:
  name: termovalvole-piano-terra
  comment: Piano terra ESP8266 Controllore termovalvole
  
  on_boot:
    then:
      - output.turn_off: gpio_d0_ground
  
esp8266:
  board: d1_mini_lite

# Enable logging
logger:

# Enable Home Assistant API 
#api:
  #password: ""

mqtt:
  broker: myhomeipdk.hopto.org

ota:
  password: "62cb9b17501ce612d0a0d0ce1de2630c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Termovalvole-Piano-Terra"
    password: "Z2mt7eGHISkl"

captive_portal:
    

switch:
  - platform: gpio
    name: "Termovalvola Piano Terra"
    id: termovalvola_piano_terra
    pin: D1 # Prima era D2
    icon: "mdi:radiator"

  - platform: gpio
    name: "Termovalvola Bagni"
    id: termovalvola_bagni
    pin: D2 # Prima era D1
    icon: "mdi:radiator"
    
sensor:
  - platform: wifi_signal
    name: "WiFi Signal termovalvole-piano-terra"
    update_interval: 60s
    filters:
      - quantile:
          window_size: 7
          send_every: 4
          send_first_at: 3
          quantile: .9


output:
  - platform: gpio
    pin: D0
    id: gpio_d0_ground

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode:
        input: true
        pullup: true
      inverted: false
    name: Termostato Muro Piano Terra
    on_press:
      - switch.turn_on: termovalvola_piano_terra
      
    on_release:
      - switch.turn_off: termovalvola_piano_terra
      

  - platform: gpio
    pin:
      number: D7
      mode:
        input: true
        pullup: true
      inverted: false
    name: Termostato Muro Bagni
    on_press:
      - switch.turn_on: termovalvola_bagni
      
    on_release:
      - switch.turn_off: termovalvola_bagni
     
    
    
    
    
    
    
    