esphome:
  name: tmp-test-device
  comment: Test temporaneo


esp8266:
  board: d1_mini_lite

# Enable logging
logger:

mqtt:
  broker: !secret mqtt_broker
  
  
# Enable Home Assistant API
# api:
#   encryption:
#     key: "S/OGno2S6t7t7GGrajPE3yWhktoCW+U7LwFL95h/7GY="


ota:
  password: "5bda3bca66e736daa257da373f1f4d57"

wifi:
  ssid: !secret wifi_ssid_dk
  password: !secret wifi_password_dk

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "TEST"
    password: "Pippero64"
    
captive_portal:


uart:
  rx_pin: D4
  baud_rate: 9600

# sensor:
#   - platform: pm1006
#     pm_2_5:
#       name: "Qualita Aria Dk Camera Andrea"

    
#   - platform: wifi_signal
#     name: "WiFi Signal qualita Aria Dk Camera-Andrea"
#     update_interval: 60s
#     filters:
#     - quantile:
#         window_size: 7
#         send_every: 4
#         send_first_at: 3
#         quantile: .9
    